### ISSUE TITLE
ImportError: cannot import name 'Arduino' from 'pyfirmata'

### ISSUE THREAD

**Issue by denuradhan** [tino/pyFirmata#105]
this is the source code :

```from pyfirmata import Arduino, util
import time
board = Arduino('COM7')
iterator = util.Iterator(board)
iterator.start()
button = board.get_pin('d:2:i')
while True:
    print(button.read())
    time.sleep(1)
```

And this is the output :
```Traceback (most recent call last):
  File "c:/Users/ASUS/Documents/Arduino/IOT/praktikum7/pyfirmata.py", line 1, in <module>
    from pyfirmata import Arduino, util
  File "c:\Users\ASUS\Documents\Arduino\IOT\praktikum7\pyfirmata.py", line 1, in <module>
    from pyfirmata import Arduino, util
ImportError: cannot import name 'Arduino' from 'pyfirmata' (c:\Users\ASUS\Documents\Arduino\IOT\praktikum7\pyfirmata.py)
```

**Comment by denuradhan** [comment]
my bad, the file name is ```pyfirmata.py``` when the program is running it will import itself not the pyfirmata library
