### ISSUE TITLE
TypeError: Board._handle_report_version() missing 1 required positional argument: 'minor'

### ISSUE THREAD

**Issue by Tanishq-JM** [tino/pyFirmata#133]
Help me i uploaded pyfirmata in by UNO board, before it was working.
2 hours ago last time i checked it worked but now its not working. please help as its my college project
```python

from pyfirmata import Arduino

board = Arduino('COM3')
```

```
Traceback (most recent call last):
  File "d:\python\test8.py", line 4, in <module>
    board = Arduino('COM3')
            ^^^^^^^^^^^^^^^
  File "C:\Users\Jayavant\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyfirmata\__init__.py", line 19, in __init__
    super(Arduino, self).__init__(*args, **kwargs)
  File "C:\Users\Jayavant\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyfirmata\pyfirmata.py", line 107, in __init__
    self.iterate()
  File "C:\Users\Jayavant\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyfirmata\pyfirmata.py", line 302, in iterate
    handler(*received_data)
  File "C:\Users\Jayavant\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyfirmata\pyfirmata.py", line 190, in decorator
    f(*args, **kwargs)
TypeError: Board._handle_report_version() missing 1 required positional argument: 'minor'
PS D:\python> 
```

**Comment by Tanishq-JM** [comment]
Replace

`len_args = len(inspect.getargspec(func)[0])
`
with

`len_args = len(inspect.getfullargspec(func)[0])`
